influx:
  image: tutum/influxdb
  ports:
    - 8086:8086
    - 8083:8083
serializer:
  build: ../services/serializer/
  container_name: serializer
frontend:
  build: ../frontend/
  container_name: frontend
